/// <reference path="typings/typescript/typescript.d.ts" />
/// <reference path="typings/angularjs/angular.d.ts" />
/// <reference path="typings/angularjs/angular-route.d.ts" />
/// <reference path="app.ts" />
/// <reference path="startup.ts" />
/// <reference path="route.ts" />
/// <reference path="interfaces/irootscope.ts" />
/// <reference path="models/usertoken.ts" />
/// <reference path="service/bearerauthinterceptor.ts" />
/// <reference path="controller/profilectrl.ts" />
/// <reference path="controller/homectrl.ts" />
/// <reference path="controller/themingctrl.ts" />
/// <reference path="controller/loginctrl.ts" />
//# sourceMappingURL=_reference.js.map